# Generated by Django 5.1.4 on 2025-03-04 01:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcedimentosPlastica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('preco_base', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProfissionalPlastica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome Completo')),
                ('especialidade', models.CharField(blank=True, max_length=200, null=True, verbose_name='Especialidade')),
                ('telefone', models.CharField(max_length=15, verbose_name='Telefone')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Atualizado em')),
            ],
        ),
        migrations.CreateModel(
            name='ContratoPlastica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('celular', models.CharField(max_length=15)),
                ('procedimento', models.TextField()),
                ('valor_total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('data_contrato', models.DateField(blank=True, null=True)),
                ('data_efetivacao', models.DateField(blank=True, null=True)),
                ('data_validade', models.DateField(blank=True, null=True)),
                ('contrato_assinado', models.ImageField(blank=True, null=True, upload_to='contratos_assinados/')),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'Sem Contrato'), (2, 'Com Contrato'), (3, 'Contrato Finalizado'), (4, 'Contrato Cancelado')], default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contratos_plastica', to='clientes.registroclientes')),
            ],
        ),
        migrations.CreateModel(
            name='PagamentoContrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_pagamento', models.DateField(blank=True, null=True)),
                ('comprovante', models.FileField(blank=True, null=True, upload_to='comprovantes/')),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagamentos', to='plastica.contratoplastica')),
            ],
        ),
        migrations.CreateModel(
            name='PreAgendamentoPlastica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('celular', models.CharField(max_length=15)),
                ('data_agendamento', models.DateField()),
                ('data_consulta', models.DateField()),
                ('horario', models.TimeField()),
                ('procedimento', models.CharField(max_length=255)),
                ('posicao_agendamento', models.PositiveSmallIntegerField(choices=[(1, 'Confirmado'), (2, 'Reagendado'), (3, 'Cancelado'), (4, 'Sem Resposta')], default=4)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agendamentos_plastica', to='clientes.registroclientes')),
            ],
            options={
                'ordering': ['data_consulta', 'horario'],
            },
        ),
        migrations.CreateModel(
            name='RegistroAtendimentoPlastica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('procedimento', models.CharField(max_length=255)),
                ('data', models.DateTimeField()),
                ('valor_pago', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('forma_pagamento', models.CharField(choices=[('Dinheiro', 'Dinheiro'), ('Cartão de Crédito', 'Cartão de Crédito'), ('Cartão de Débito', 'Cartão de Débito'), ('Pix', 'Pix'), ('Outro', 'Outro'), ('Cortesia', 'Cortesia')], max_length=100)),
                ('parcelas', models.IntegerField(blank=True, default=1, null=True)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='atendimentos_plastica', to='clientes.registroclientes')),
                ('profissional', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='atendimentos_plastica', to='plastica.profissionalplastica')),
            ],
            options={
                'ordering': ['-data'],
            },
        ),
        migrations.CreateModel(
            name='HistoricoProcedimentosPlastica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('procedimento', models.CharField(max_length=255)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico_procedimentos_plastica', to='clientes.registroclientes')),
                ('profissional', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='historico_procedimentos_plastica', to='plastica.profissionalplastica')),
                ('atendimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico_procedimentos_plastica', to='plastica.registroatendimentoplastica')),
            ],
        ),
    ]
