# Generated by Django 5.1.4 on 2025-02-22 12:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroClientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400, verbose_name='Nome Completo')),
                ('d_nasc', models.DateField(blank=True, null=True, verbose_name='Data de Nascimento')),
                ('cpf', models.CharField(max_length=14, unique=True, verbose_name='CPF')),
                ('telefone', models.CharField(blank=True, max_length=15, null=True, verbose_name='Telefone')),
                ('telefone2', models.CharField(blank=True, max_length=15, null=True, verbose_name='Telefone Secundário')),
                ('endereco', models.CharField(max_length=300, verbose_name='Endereço')),
                ('numero', models.CharField(blank=True, max_length=10, null=True, verbose_name='Número')),
                ('complemento', models.CharField(blank=True, max_length=100, null=True, verbose_name='Complemento')),
                ('bairro', models.CharField(blank=True, max_length=100, null=True, verbose_name='Bairro')),
                ('cidade', models.CharField(blank=True, max_length=100, null=True, verbose_name='Cidade')),
                ('estado', models.CharField(blank=True, max_length=50, null=True, verbose_name='Estado')),
                ('cep', models.CharField(max_length=9, verbose_name='CEP')),
                ('rg', models.CharField(blank=True, max_length=20, null=True, verbose_name='RG')),
                ('sexo', models.CharField(blank=True, choices=[('masculino', 'Masculino'), ('feminino', 'Feminino'), ('nao_dizer', 'Prefiro não dizer')], max_length=15, null=True, verbose_name='Sexo')),
                ('formacao', models.CharField(blank=True, choices=[('primaria', 'Primária'), ('secundaria', 'Secundária'), ('superior', 'Superior')], max_length=15, null=True, verbose_name='Formação')),
                ('ocupacao', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ocupação/Função')),
                ('plano_saude', models.BooleanField(default=False, verbose_name='Possui Plano de Saúde?')),
                ('nome_plano', models.CharField(blank=True, max_length=150, null=True, verbose_name='Nome do Plano de Saúde')),
                ('email', models.EmailField(blank=True, max_length=150, null=True, verbose_name='E-mail')),
                ('acao', models.CharField(choices=[('google', 'Google'), ('facebook', 'Facebook'), ('formulario', 'Formulário'), ('instagram', 'Instagram'), ('amigo', 'Amigo'), ('parente', 'Parente'), ('outros', 'Outros')], default='instagram', max_length=50, verbose_name='Ação de Origem')),
                ('tipo_cliente', models.CharField(choices=[('estetica', 'Somente Estética'), ('plastica', 'Somente Plástica'), ('ambos', 'Plástica e Estética')], default='estetica', max_length=50, verbose_name='Tipo de Cliente')),
                ('estado_civil', models.CharField(blank=True, choices=[('solteiro', 'Solteiro(a)'), ('casado', 'Casado(a)'), ('divorciado', 'Divorciado(a)'), ('viuvo', 'Viúvo(a)'), ('uniao_estavel', 'União Estável'), ('outros', 'Outros')], default='solteiro', max_length=20, null=True, verbose_name='Estado Civil')),
                ('restricao', models.TextField(blank=True, null=True, verbose_name='Restrições')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Registro de Cliente',
                'verbose_name_plural': 'Registros de Clientes',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='HistoricoClientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consulta_em', models.DateField(auto_now_add=True, verbose_name='Consultado em')),
                ('acao', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ação Realizada')),
                ('tipo_cliente', models.CharField(default='estetica', max_length=50, verbose_name='Tipo de Cliente')),
                ('ultima_atualizacao', models.DateTimeField(blank=True, null=True, verbose_name='Última Atualização')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico', to='clientes.registroclientes')),
            ],
            options={
                'verbose_name': 'Histórico de Cliente',
                'verbose_name_plural': 'Históricos de Clientes',
                'ordering': ['-consulta_em'],
            },
        ),
    ]
